### ISSUE TITLE
TECH: Use get_plugin_config() instead of template sensor TZ in package.yaml

### ISSUE THREAD

**Issue by ArdJonker** [V2G-liberty/addon-v2g-liberty#103]
get_plugin_config() provides:
- Currency
- Timezone
- Length (km)
- Name of HA instance (replace from v2g_liberty.py)
- Country (pre-select for electricity-providers?)

Use in globals:
```python
config = await self.get_plugin_config()
```

Replaces:
```yaml
template:
  - sensor:
    # To make the HA time_zone available to the V2G Liberty python code.
    - name: Time Zone
      unique_id: time_zone
      state: "{{ now().tzinfo }}"
```
